# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: 'demo-avalora-veracode'
    replaceExistingArchive: true

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: '632492030ee31b5035f39b120d753207'
    apiKey: 'e1693bd487bd53bce16d9a87a3e84e60b7e6b684908d9c0d5cafb56744ad7bbba485333029bbdf2195b7c523b4b0bae87986be0b6951875d0fb45061d23804c4'
    veracodeAppProfile: 'Demo POC veracode'
    sandboxName: 'Damian Ortiz'
    version: '$(build.buildNumber)'
    filepath: 'demo-avalora-veracode.zip'
    maximumWaitTime: '360'