# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: 'demo-veracode'
    replaceExistingArchive: true

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: '69d32b48a0313c9a3ef7f270c7f7e8f7'
    apiKey: 'fcf9a5a7f7cff747c072fbde3da2f54ec8e0a0efca0515cfb47373bd2fe758342d0a5da97c27f3f0c5e966d3630c4f3eb8681aa4221a597de81c6ec34cbbb7eb'
    veracodeAppProfile: 'Demo POC veracode'
    version: '$(build.buildNumber)'
    filepath: 'demo-veracode.zip'
    sandboxName: 'Damian Ortiz'
    maximumWaitTime: '360'