# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: '27bc1b69ae79387dce8cc314d1bb5126'
    apiKey: 'a8f1039f1b765f75631053bba405891afd3b9c8874e2cb2c658695078a8c2fc8858267b616af11e7ae56e1235e68e0134b46edd101633cfcb87d45eacead16c9'
    veracodeAppProfile: 'Demo POC veracode'
    sandboxName: 'dammii96'
    version: '$(build.buildNumber)'
    filepath: './demo-avalora-veracode.zip'
    maximumWaitTime: '360'